name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iris: [3.6.0, 4.0.0]
        coq: [8.15]
        include:
          - iris: 4.0.0
            coq: 8.16
    env:
      COQ_VERSION: ${{ matrix.coq }}
      IRIS_VERSION: ${{ matrix.iris }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            COQ_VERSION=${{ env.COQ_VERSION }}
            IRIS_VERSION=${{ env.IRIS_VERSION }}
          tags: blaisorblade/docker-dot-iris:coq-${{ env.COQ_VERSION }}-iris-${{ env.IRIS_VERSION }}
